[program:license]
directory=/var/www
command=sh docker/php/license.sh
numprocs=1
autostart=true
autorestart=true
startretries=100
user=root
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
