# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Release
on:
  release:
    types: [published]
jobs:
  releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
      - run: npm install
      - run: npx mix --production
      - run: cd ../ && tar --exclude-vcs --exclude .github --exclude tests --exclude node_modules -zcf dootask.tar.gz dootask/ && mv dootask.tar.gz dootask/ && cd dootask
      - name: Uploading assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dootask.tar.gz
          asset_name: dootask-${{github.event.release.tag_name}}.tar.gz
          asset_content_type: application/tar+gzip
