# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Release
on:
  release:
    types: [published]
jobs:
  bundles:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
      - run: npm install
      - run: npx mix --production
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.21.0
        with:
          php-version: '8.0'
      - run: php app/Http/Controllers/Api/apidoc.php
      - run: npm install -g apidoc
      - run: apidoc -i app/Http/Controllers/Api -o ./public/docs
      - run: tar -zcf assets.tar.gz public
      - name: Uploading assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./assets.tar.gz
          asset_name: dootask-${{github.event.release.tag_name}}-assets.tar.gz
          asset_content_type: application/tar+gzip
      - run: composer update
      - run: php bin/run --mode=prod
      - run: tar -zcf dootask-laravel.tar.gz app bin bootstrap config database routes vendor artisan cmd composer.json composer.lock version.js server.php storage resources public
      - name: Uploading bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dootask-laravel.tar.gz
          asset_name: dootask-${{github.event.release.tag_name}}-laravel.tar.gz
          asset_content_type: application/tar+gzip
      - run: cp dootask-laravel.tar.gz ./docker-package/php/dootask.tar.gz
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: "${{env.DOCKERHUB_USERNAME != ''}}"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: "${{env.DOCKERHUB_USERNAME != ''}}"
        uses: docker/build-push-action@v3
        with:
          context: ./docker-package/php
          file: ./docker-package/php/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/dootask-php:${{github.event.release.tag_name}},${{ env.DOCKERHUB_USERNAME }}/dootask-php:latest
